/* Generated by Together */

package com.om.onec.junit;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

/** Simple class to build a TestSuite out of the individual test classes. */
public class AllJUnitTests extends TestCase {
    public AllJUnitTests(String name) {
        super(name);
    }

    public static Test suite() {
        TestSuite suite = new TestSuite();
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.cci.TestResultSetImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.cci.TestRecordImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.cci.TestRecordFactoryImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.cci.TestMappedRecordImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.cci.TestInteractionSpecImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.cci.TestInteractionImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.cci.TestConnectionImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.cci.TestConnectionFactoryImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.spi.TestManagedConnectionFactoryImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.spi.TestManagedConnectionImpl.class));
        suite.addTest(new TestSuite(com.om.onec.junit.unit.com.om.onec.adapter.spi.TestDefaultConnectionManager.class));
        suite.addTest(new TestSuite(com.om.onec.junit.acceptance.acceptanceTest.class));
        return suite;
    }
}
