/* Generated by Together */


import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

/** Simple class to build a TestSuite out of the individual test classes. */
public class AllJUnitTests extends TestCase {
    public AllJUnitTests(String name) {
        super(name);
    }

    public static Test suite() {
        TestSuite suite = new TestSuite();
        suite.addTest(new TestSuite(unit.com.om.onec.cci.TestResultSetImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.cci.TestRecordImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.cci.TestRecordFactoryImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.cci.TestMappedRecordImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.cci.TestInteractionSpecImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.cci.TestInteractionImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.cci.TestConnectionImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.cci.TestConnectionFactoryImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.spi.TestManagedConnectionFactoryImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.spi.TestManagedConnectionImpl.class));
        suite.addTest(new TestSuite(unit.com.om.onec.spi.TestDefaultConnectionManager.class));
        suite.addTest(new TestSuite(acceptance.acceptanceTest.class));
        return suite;
    }
}
