/* Generated by Together */

package Session;

import javax.ejb.EJBHome;
import javax.ejb.CreateException;
import javax.ejb.EJBException;
import java.rmi.RemoteException;

public interface ClientHome extends EJBHome {
    Client create() throws CreateException, EJBException, RemoteException;

    /** @link dependency */

    /*#ClientBean lnkSession1Bean;*/
}
