/* Generated by Together */

package Session;

import com.om.onec.cci.*;
import com.om.onec.DocumentDesc;
import javax.ejb.EJBObject;
import java.rmi.RemoteException;
import javax.ejb.EJBException;
import javax.resource.ResourceException;

public interface TestConnector extends EJBObject {
    boolean getConnection() throws RemoteException, EJBException;

    boolean lookupFactory(String factoryName) throws RemoteException, EJBException;

    boolean closeConnection() throws RemoteException, EJBException;

    int testJavaTestAsInt(int aValue) throws RemoteException, EJBException, ResourceException;

    ConnectionFactoryImpl getConnectionFactory() throws RemoteException, EJBException;

    ConnectionImpl getConnectionHandle() throws RemoteException, EJBException;

    void testWriteData(DocumentDesc dd)throws RemoteException, EJBException, ResourceException;

    /** @link dependency */

    /*#TestConnectorBean lnkSession1Bean;*/
}
