/* Generated by Together */

package unit.com.om.onec.cci;

import junit.framework.*;
import junitx.framework.*;
import javax.resource.cci.InteractionSpec;
import com.om.onec.cci.InteractionSpecImpl;
import javax.resource.ResourceException;
import onec.IDispatchProxy;
import com.linar.jintegra.*;
import com.om.onec.AuthProperties;

/**
 * @author
 * @number 1.2
 * @description This class tests InteractionSpecImpl
 * @input
 * @output
 */
public class TestInteractionSpecImpl extends TestCase {
	private InteractionSpecImpl isi;
	private IDispatchProxy d_object;

	/** Constructs a test case with the given name. */
	public TestInteractionSpecImpl(String name) {
		super(name);
	}

	/** Sets up the fixture. This method is called before a test is executed. */
	protected void setUp() throws ResourceException, java.net.UnknownHostException, java.io.IOException {
		isi = new InteractionSpecImpl(0, "test_name1");
        d_object = new IDispatchProxy("BF417C70-9A34-11D2-9F3D-008048DA120F", "127.0.0.1", (new AuthProperties()).getAuthInfo());
    }

    protected void tearDown() {
		com.linar.jintegra.Cleaner.release(d_object);
	}

    public void testGetFName() throws ResourceException {
		assertEquals("Unable to get function name...", isi.getFunctionName(), "test_name1");
		System.out.println("Method getFunctionName tested.");
    }
	public void testSetFName() throws ResourceException {
		isi.setFunctionName("test_name2");
        assertEquals("Unable to set function name...", isi.getFunctionName(), "test_name2" );
        System.out.println("Method serFunctionName tested.");
    }
    public void testGetFMethod() throws ResourceException {
		assertEquals("Unable to get function method...", isi.getFunctionMethod(), 0);
        System.out.println("Method getFunctionMethod tested.");
    }
	public void testSetFMethod() throws ResourceException {
		isi.setFunctionMethod(1);
        assertEquals("Unable to set function method...", isi.getFunctionMethod(), 1);
        System.out.println("Method setFunctionMethod tested.");
    }
    public void testDispatchObject() throws ResourceException {
		isi.setDispatchObject(d_object);
        assertNotNull("Unable to set dispatch object...", isi.getDispatchObject());
        System.out.println("Methods set/getDispatchObject tested.");
		System.out.println("\nTests done.");
    }
}