/* Generated by Together */

package com.om.onec.junit.unit.com.om.onec.adapter.cci;

import junit.framework.*;
import junitx.framework.*;

import com.om.onec.adapter.spi.*;
import com.om.onec.adapter.cci.*;
import com.om.onec.common.*;
import com.linar.jintegra.*;

import java.io.IOException;

import javax.resource.ResourceException;

public class TestConnectionImpl extends TestCase {
    private ManagedConnectionFactoryImpl mcf;
    private ManagedConnectionImpl mc;
    private InteractionImpl i;
    private ConnectionImpl c;

    public TestConnectionImpl(String name) {
        super(name);
    }

    public void setUp() throws IOException, ResourceException {
        com.linar.jintegra.Cleaner.trackObjectsInCurrentThread();
	    com.linar.jintegra.AuthInfo.setThreadDefault((new AuthProperties()).getAuthInfo());

        mcf = new ManagedConnectionFactoryImpl();

        OneCDBProperties dbp = new OneCDBProperties();

        mcf.setDbPath(dbp.getDBPath());
        mcf.setUserName(dbp.getUserName());
        mcf.setPassword(dbp.getPassword());

        mc = (ManagedConnectionImpl)mcf.createManagedConnection(null, null);

        c = new ConnectionImpl(mc);

    }

    public void tearDown() throws ResourceException {
        if(mc.getClient()!=null) mc.destroy();
        mc=null;

        mcf=null;
        i=null;

        com.linar.jintegra.Cleaner.releaseAllInCurrentThread();
	    com.linar.jintegra.AuthInfo.setThreadDefault(null);

    }

    public void testCreateInteraction() throws ResourceException {
        assertNotNull("Unable to create interaction", c.createInteraction());
    }

    public void testGetManagedConnection() throws ResourceException {
        assertNotNull("Unable to get ManagedConnection", c.getManagedConnection());
    }

    public void testClose() throws ResourceException {
        c.close();
        assertNull("Close failed", c.getManagedConnection());
    }

}
