/* Generated by Together */

package unit.com.om.onec.cci;

import junit.framework.*;
import junitx.framework.*;
import javax.resource.cci.RecordFactory;
import javax.resource.cci.MappedRecord;
import com.om.onec.cci.*;
import javax.resource.ResourceException;

/**
 * @author
 * @number 1.2
 * @description This class tests RecordFactoryImpl for creating MappedRecord and IndexedRecord instances
 * @input
 * @output
 */
public class TestRecordFactoryImpl extends TestCase {
	protected RecordFactoryImpl rfi;

    /** Constructs a test case with the given name. */
    public TestRecordFactoryImpl(String name) {
        super(name);
    }

    /*Sets up the fixture. This method is called before a test is executed. */
	protected void setUp() {
		rfi = new RecordFactoryImpl();
    }

    /*Testing method createMappedRecord*/
	public void testMappedRecord() throws ResourceException {
		MappedRecordImpl mri = (MappedRecordImpl)rfi.createMappedRecord("TestMappedRecord");
        assertNotNull("Error creating MappedRecord.", mri);
        System.out.println("\nMetod createMappedRecord tested ...");
	}

    /*Testing method createIndexedRecord*/
    public void testIndexedRecord() throws ResourceException {
		try {
				MappedRecordImpl iri = (MappedRecordImpl)rfi.createIndexedRecord("TestIndexedRecord");
		} catch (ResourceException re) {System.out.println("\nMethod createIndexRecored tested ...");}
		System.out.println("\nTests done ...");
    }
}

