/* Generated by Together */

package com.om.onec.junit.feature;

import com.om.onec.adapter.spi.*;
import junit.framework.*;

public class DefaultConnectionManagerTest extends TestCase {
    protected ManagedConnectionFactoryImpl m_managedConnectionFactory;

    public static Test suite() {
        return new TestSuite(DefaultConnectionManagerTest.class);
    }

    protected void setUp() {
        m_managedConnectionFactory = new ManagedConnectionFactoryImpl();
    }

    public DefaultConnectionManagerTest(String name) {
        super(name);
    }

    public void testing() {
        try {
            System.out.println("[DefaultConnectionManagerTest] starting test...");
            assertNotNull("ManagedConnectionFactory was not created.", m_managedConnectionFactory);
            DefaultConnectionManager defaultConnectionManager = new DefaultConnectionManager();
            assertNotNull("DefaultConnectionManager was not created.", defaultConnectionManager);
            assertNotNull("AllocateConnection failed.",
                defaultConnectionManager.allocateConnection(m_managedConnectionFactory, null));
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("[DefaultConnectionManagerTest] finished testing...");
    }

    public void main(String[] argv) {
        testing();
    }
}
