/* Generated by Together */

package feature;

import com.om.onec.spi.*;
import com.om.onec.cci.ConnectionImpl;
import javax.resource.spi.*;
import javax.resource.NotSupportedException;
import javax.security.auth.Subject;
import java.io.PrintWriter;
import junit.framework.*;

/** @author Andrej N. Chuchalov */
public class ManagedConnectionImplTest extends TestCase {
    protected Subject m_subject;
    protected DefaultConnectionManager m_defaultConnectionManager;

    public static Test suite() {
        return new TestSuite(ManagedConnectionImplTest.class);
    }

    public ManagedConnectionImplTest(String name) {
        super(name);
    }

    public void testing() {
        try {
            System.out.println("[ManagedConnectionImpl] starting test...");

/*            Object invalidObject = (Object)System.out;
            assertNotNull("Unable to assign test object", invalidObject);*/

            ManagedConnectionFactoryImpl managedConnectionFactory = new ManagedConnectionFactoryImpl();
            assertNotNull("Unable to create ManagedConnectionFactory", managedConnectionFactory);
            ManagedConnectionImpl managedConnection =
                //                (ManagedConnectionImpl)m_defaultConnectionManager.allocateConnection(managedConnectionFactory, null);
                new ManagedConnectionImpl(managedConnectionFactory, m_subject, null);
            assertNotNull("Unable to allocate connection", managedConnection);

/*			managedConnection = (ManagedConnectionImpl)m_defaultConnectionManager.allocateConnection((ManagedConnectionFactoryImpl)invalidObject, null);
            assertNotNull("Unable to allocate connection", managedConnection);
			managedConnection = (ManagedConnectionImpl)m_defaultConnectionManager.allocateConnection(null, null);
            assertNotNull("Unable to allocate connection", managedConnection);*/

            ConnectionImpl connection = (ConnectionImpl)managedConnection.getConnection(m_subject, null);
            assertNotNull("Could not get a Connection", connection);

/*            connection = (ConnectionImpl)managedConnection.getConnection((Subject)invalidObject, null);
            assertNotNull("Could not get a Connection", connection);
            connection = (ConnectionImpl)managedConnection.getConnection(null, null);
            assertNotNull("Could not get a Connection", connection);*/

            managedConnection.associateConnection(connection);

/*            managedConnection.associateConnection((ConnectionImpl)invalidObject);
            managedConnection.associateConnection(null);*/

            managedConnection.cleanup();
            managedConnection.destroy();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("[ManagedConnectionImpl] finished testing...");
    }

    public void setUp() {
        m_subject = new Subject();
        //        m_defaultConnectionManager = new DefaultConnectionManager();
    }

    public void main(String[] args) {
        testing();
    }
}
