/* Generated by Together */

package feature;

import com.om.onec.cci.ResultSetImpl;
import com.om.onec.cci.RecordImpl;

public class ResultSetImplTest {
    public static void main(String[] args) {
        try {
	        System.out.println("Starting test");
	        System.out.println("creating record");
    	    RecordImpl ri = new RecordImpl("Test");
	        System.out.println("creating resultset");
        	ResultSetImpl rsi = new ResultSetImpl(ri);

	        System.out.println("adding string \"Test String\"");
	        String testString = "Test String";
    	    rsi.updateString("Param", testString);

	        System.out.println("retrieving result");
            testString = rsi.getString("Param");
	        System.out.println("result is: \""+testString+"\"");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
