/* Generated by Together */

package com.om.onec.cci;

import javax.resource.cci.InteractionSpec;

import java.io.Serializable;

import onec.IDispatchProxy;
import com.om.onec.AuthProperties;

/**
* @author Andrej N. Chuchalov
* @version 1.2
* class defines function execution rules
* */
public class InteractionSpecImpl implements InteractionSpec, Serializable {
    private String m_functionName; //stores function name
    private int m_functionMethod; //stores function method

    private IDispatchProxy m_dispObj; //stores dispatch object

    public static final int MID_CALL=0; //method Call constant
    public static final int MID_GET=1; //get property constant
    public static final int MID_PUT=2; //put property constant

    //class constructor
    public InteractionSpecImpl(int method, String functionName) {
        this.m_functionName = functionName;
        this.m_functionMethod = method;
    }

    //functionName mutator
    public void setFunctionName(String functionName) {
        m_functionName = functionName;
    }

    //functionName accessor
    public String getFunctionName() {
        return m_functionName;
    }

    //functionMethod mutator
    public void setFunctionMethod(int method) {
        this.m_functionMethod = method;
    }

    //functionMethod accessor
    public int getFunctionMethod() {
        return this.m_functionMethod;
    }

    //dispatchObject mutator
    public void setDispatchObject(IDispatchProxy object) {
	this.m_dispObj = object;
    }

    //dispatchObject accessor
    public IDispatchProxy getDispatchObject() {
        return this.m_dispObj;
    }
}
