/* Generated by Together */

package com.om.onec;

import java.util.Properties;
import java.io.*;
import com.linar.jintegra.AuthInfo;

public class AuthProperties {
    private Properties props;

    public AuthProperties() throws IOException {
        props = new Properties();
        FileInputStream fis = new FileInputStream(
            System.getProperty("JCA1C_HOME")+"\\META-INF\\authinfo.properties");
        props.load(fis);
    }

    public Properties getProperties() {
        return this.props;
    }

    public String getUserName() {
        return this.props.getProperty("User");
    }

    public String getPassword() {
        return this.props.getProperty("Password");
    }

    public String getDomain() {
        return this.props.getProperty("Domain");
    }

    public AuthInfo getAuthInfo() {
        return new AuthInfo(getDomain(), getUserName(), getPassword());
    }
}
