/* Generated by Together */

package com.om.onec;

import java.io.Serializable;

public class DocumentDesc implements Serializable {
    public float getCode(){
            return code;
        }

    public void setCode(float code){
            this.code = code;
        }

    public float getQuantity(){
            return quantity;
        }

    public void setQuantity(float quantity){
            this.quantity = quantity;
        }

    public float getPrice(){
            return price;
        }

    public void setPrice(float price){
            this.price = price;
        }

    private float code=2018;
    private float quantity=5;
    private float price=14;
}
