/* Generated by Together */

package com.om.onec;

import java.util.Properties;
import java.io.*;

public class OneCDBProperties {
    private Properties props;

    public OneCDBProperties() throws IOException {
        props = new Properties();
        FileInputStream fis = new FileInputStream(
            System.getProperty("JCA1C_HOME")+"/META-INF/onecdb.properties");
        props.load(fis);
    }

    public Properties getProperties() {
        return this.props;
    }

    public String getUserName() {
        return this.props.getProperty("User");
    }

    public String getPassword() {
        return this.props.getProperty("Password");
    }

    public String getDBPath() {
        return this.props.getProperty("DbPath");
    }

}
