/* Generated by Together */

package Session.remote;

import javax.ejb.EJBHome;
import javax.ejb.CreateException;
import javax.ejb.EJBException;
import java.rmi.RemoteException;

public interface TestConnectorHome extends EJBHome {
    TestConnector create() throws CreateException, EJBException, RemoteException;

    /** @link dependency */

    /*#TestConnectorBean lnkSession1Bean;*/
}
