/* Generated by Together */

package com.om.onec.spi;

import java.io.Serializable;
import javax.resource.cci.ConnectionMetaData;
import javax.resource.spi.ManagedConnectionMetaData;

/**
 * The ManagedConnectionMetaData provides information about a ManagedConnection and the connected EIS instance.
 * @author Andrej N. Chuchalov
 */
public class ManagedConnectionMetaDataImpl implements ManagedConnectionMetaData, ConnectionMetaData, Serializable {
    public ManagedConnectionMetaDataImpl(String eisProductName, String eisProductVersion,
        int maxConnections, String userName) {
            m_eisProductName = eisProductName;
            m_eisProductVersion = eisProductVersion;
            m_maxConnections = maxConnections;
            m_userName = userName;
    }

    public String getEISProductName() {
        return m_eisProductName;
    }

    public String getEISProductVersion() {
        return m_eisProductVersion;
    }

    public int getMaxConnections() {
        return m_maxConnections;
    }

    public String getUserName() {
        return m_userName;
    }

    public String toString() {
        return String.valueOf(String.valueOf(
            new StringBuffer("[ManagedConnectionMetaData]\n\tEISProductName = ").append(m_eisProductName).append("\n\t").append("EISProductVersion = ").append(m_eisProductVersion).append("\n\t").append("UserName = ").append(m_userName)));
    }

    private String m_eisProductName;

    /** @author Squat */
    private String m_eisProductVersion;
    private int m_maxConnections;
    private String m_userName;
}
